name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: fduartej1/appfunko:latest
          access-token: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  deploy-to-render:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Login to Render
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"username":"'"${{ secrets.RENDER_EMAIL }}"'","password":"'"${{ secrets.RENDER_PASSWORD }}"'"}' \
            https://render.com/api/auth/login > render.json
          export TOKEN=$(jq -r .token render.json)

      - name: Deploy to Render
        run: |
          curl -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -X POST \
            -d '{"imageName":"fduartej1/appfunko:latest","name":"appfunko"}' \
            https://render.com/api/v1/services
